# Change these first
owner: constructions-incongrues # Your GitHub organization or username, where this repository lives
repo: status-pantagruweb # The name of this repository

sites:
  - name: Home
    url: https://pantagruweb.club
  - name: Baloche
    url: https://baloche.pantagruweb.club
  - name: Cinoche
    url: https://cinoche.pantagruweb.club
  - name: Cocagne
    url: https://cocagne.pantagruweb.club
  - name: Panurge
    url: https://panurge.pantagruweb.club
    
assignees:
  - trivoallan

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pantagruweb.club
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: Pantagruweb
  navbar:
    - title: Constructions
      href: https://status.constructions-incongrues.net
    - title: Interzone
      href: https://status.interzone.network
    - title: Pastis
      href: https://pastis-hosting.net
